# Generated by Django 4.2.1 on 2023-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='mobile',
            new_name='huyen',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='quan',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='thanhpho',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='sodt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
