# Generated by Django 4.2.1 on 2023-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_mobile_shippingaddress_huyen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='quantity',
            new_name='thanh_pho',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='thanhpho',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='huyen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='sodt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
