# Generated by Django 4.2.1 on 2023-06-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_shippingaddress_order_order_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='thanh_pho',
            new_name='thanhpho',
        ),
    ]
