# Generated by Django 4.2.1 on 2023-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_thanh_pho_shippingaddress_thanhpho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='sodt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
