# Generated by Django 4.2.1 on 2023-06-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer_address',
        ),
    ]
