# Generated by Django 4.2.1 on 2023-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(related_name='products', to='app.review'),
        ),
    ]
